import formatTransactionDate from '../../utils/formatTransactionDate';

export const ELEMENT_DATA: any[] = [
  {
    id: 1,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 2,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 3,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 4,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 5,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 6,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 7,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 8,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 9,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 10,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 11,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 12,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 13,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 14,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 15,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 16,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 17,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 18,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 19,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 20,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 21,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 22,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 23,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 24,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
  {
    id: 25,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    transactionValue: 4,
    transactionDate: formatTransactionDate(new Date()),
  },
];
