import { Transaction } from '../../models/transactions.model';
import formatTransactionDate from '../../utils/formatTransactionDate';

export const TRANSACTION_DETAILS: Transaction[] = [
  {
    id: 1,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-09T00:00:00')),
    receivedValue: 22.5,
  },
  {
    id: 2,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 12,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-08T00:00:00')),
    receivedValue: 24,
  },
  {
    id: 3,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 14,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-07T00:00:00')),
    receivedValue: 25.5,
  },
  {
    id: 4,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-06T00:00:00')),
    receivedValue: 27,
  },
  {
    id: 5,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 12,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-05T00:00:00')),
    receivedValue: 22.5,
  },
  {
    id: 6,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 14,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-04T00:00:00')),
    receivedValue: 24,
  },
  {
    id: 7,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-03T00:00:00')),
    receivedValue: 25.5,
  },
  {
    id: 8,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 12,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-02T00:00:00')),
    receivedValue: 27,
  },
  {
    id: 9,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 14,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-12-01T00:00:00')),
    receivedValue: 22.5,
  },
  {
    id: 10,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-30T00:00:00')),
    receivedValue: 24,
  },
  {
    id: 11,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 12,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-29T00:00:00')),
    receivedValue: 25.5,
  },
  {
    id: 12,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 14,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-28T00:00:00')),
    receivedValue: 27,
  },
  {
    id: 13,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-27T00:00:00')),
    receivedValue: 22.5,
  },
  {
    id: 14,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 12,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-26T00:00:00')),
    receivedValue: 24,
  },
  {
    id: 15,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 14,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-25T00:00:00')),
    receivedValue: 25.5,
  },
  {
    id: 16,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-24T00:00:00')),
    receivedValue: 27,
  },
  {
    id: 17,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 12,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-23T00:00:00')),
    receivedValue: 22.5,
  },
  {
    id: 18,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 14,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-22T00:00:00')),
    receivedValue: 24,
  },
  {
    id: 19,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-21T00:00:00')),
    receivedValue: 25.5,
  },
  {
    id: 20,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 12,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-20T00:00:00')),
    receivedValue: 27,
  },
  {
    id: 21,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 14,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-19T00:00:00')),
    receivedValue: 22.5,
  },
  {
    id: 22,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-18T00:00:00')),
    receivedValue: 24,
  },
  {
    id: 23,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 12,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-17T00:00:00')),
    receivedValue: 25.5,
  },
  {
    id: 24,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 14,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-16T00:00:00')),
    receivedValue: 27,
  },
  {
    id: 25,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 10,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date('2024-11-15T00:00:00')),
    receivedValue: 22.5,
  },
];
