import { Transaction } from '../../models/transactions.model';
import formatTransactionDate from '../../utils/formatTransactionDate';

export const TRANSACTION_DETAILS: Transaction[] = [
  {
    id: 1,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 2,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 3,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 4,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 5,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 6,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 7,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 8,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 9,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 10,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 11,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 12,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 13,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 14,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 15,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 16,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 17,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 18,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 19,
    sourceCurrency: 'Ouro Real',
    targetCurrency: 'Tibar',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 20,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 21,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 22,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 23,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 24,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
  {
    id: 25,
    sourceCurrency: 'Tibar',
    targetCurrency: 'Ouro Real',
    paidValue: 6,
    clientName: 'João Anão',
    transactionDate: formatTransactionDate(new Date()),
    receivedValue: 15,
  },
];
